apiVersion: v1
kind: Service
metadata:
  name: example-prod
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80        # The port exposed by the service
      targetPort: 8082 # The port your application is running on in the pod
   
